service: authorization-service
frameworkVersion: "3"

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  stage: dev
  runtime: nodejs18.x
  region: us-east-1

functions:
  basicAuthorizer:
    handler: handlers/basicAuthorizer.handler
    events:
      - http:
          path: /import
          method: get
          cors: true

resources:
  Outputs:
    BasicAuthorizerLambdaFunctionQualifiedArn:
      Export:
        Name: BasicAuthorizer-${sls:stage}