service: product-service
frameworkVersion: "3"

plugins:
  - serverless-webpack
  - serverless-auto-swagger
  - serverless-dynamodb
  - serverless-offline # must be loaded after dynamodb
  - serverless-offline-watcher

provider:
  name: aws
  stage: dev
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

  autoswagger:
    apiType: http
    typefiles: []
    basePath: /dev

  serverless-dynamodb:
    start:
      port: 8000
      docker: false
      seed: true
      migrate: true
    seed:
      products:
        sources:
          - table: products
            sources: [./database/seed/products.json]
          - table: stocks
            sources: [./database/seed/stocks.json]
  
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3001

  serverless-offline-watcher:
    - path: /**/*

functions:
  createProduct:
    handler: handlers/createProduct.handler
    events:
      - http:
          method: post
          path: products
          cors: true
  getProductsList:
    handler: handlers/getProductsList.handler
    events:
      - http:
          method: get
          path: products
          cors: true
  getProductById:
    handler: handlers/getProductsById.handler
    events:
      - http:
          method: get
          path: products/{productId}
          cors: true
          request:
            parameters:
              paths:
                productId: true

resources:
  Resources:
    products:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: products
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    stocks:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: stocks
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
  