service: import-service
frameworkVersion: "3"

plugins:
  - serverless-webpack
  - serverless-auto-swagger
  - serverless-offline
  - serverless-offline-watcher
  - serverless-s3-local

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  autoswagger:
    apiType: http
    typefiles: []
    basePath: /dev
  serverless-offline-watcher:
    - path: /**/*

functions:
  importFileParser:
    handler: handlers/importFileParser.handler
    events:
      - s3:
          bucket: ${self:provider.environment.AWS_S3_BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
          forceDeploy: true
  importProductsFile:
    handler: handlers/importProductsFile.handler
    events:
      - http:
          path: import
          method: get
          request:
            parameters:
              querystrings:
                name: true
  